### ISSUE TITLE
Distinguish the cases of optional Message fields and non-optional Message fields for PHP classes generated by protobuf

### ISSUE THREAD

**Issue by hkdevandla** [googleapis/gapic-generator-php#352]
For primitive fields, they're distinguishable--those that are optional will have hasser, getter, setter, clearer, those that are not will have getter and setter only.
For Message fields, they seem to be the same. For example, based on this definition, selective_optimization is an optional Message field, whereas dynamic_setting is not.

However, when this definition is generated as a class, both fields have exactly the same methods (hasser, getter, setter, clearer).
On the other hand, name (non-optional) and description (optional) are correctly generated to have two methods (getter and setter) and four methods (hasser, getter, setter, clearer), respectively.
It's important to be able to distinguish both cases, when implementing our field mask utility

**Comment by noahdietz** [comment]
This concerns the protobuf generated code, not gapic-generator-php generated code. We cannot do anything about those types in this project. I recommend the issue be raised in the [protobuf repo](https://github.com/protocolbuffers/protobuf/issues).

In reality though, a field of type `Message` should not be labeled with `proto3_optional` - that label is intended for primitive fields. The default, unset value for fields of type `Message` is already `null`, thus the end user can determine if the field has been set or not. Finally, in the aforementioned "field mask utility", they can just check if the type has the "hasser" method on it using `method_exists` (https://www.php.net/manual/en/function.method-exists.php).
