### ISSUE TITLE
Generate resource name helpers for resources referenced at any level of request messages

### ISSUE THREAD

**Issue by PierrickVoulet** [googleapis/gapic-generator-php#453]
**Is your feature request related to a problem? Please describe.**

The generator generates resource name helpers for resources that are referenced in top-level messages _only_.

The Google Ads API contains resources that are only referenced deep down in request messages. The library `google-ads-php` for the Google Ads API relies heavily on the generated resource name helpers.

**Describe the solution you'd like**

Generate resource name helpers for resources referenced at any level of request messages, not only in top-level messages.

**Describe alternatives you've considered**

Historically, we worked around this limitation in the library `google-ads-php` by manually implementing resource name helpers that were not automatically generated but we now have too many of those (60+) to continue working with this workaround.

**Additional context**

The issue was initially reported at b/161259389, you can find more context and some examples there.

**Comment by PierrickVoulet** [comment]
There is another consequence for this limitation:

Let's say I have a top-level message X that triggers the generation of resource name helper Y and my library users leverage this last to build or parse resource names. This is typically useful in unit tests or to build unrelated requests that reference the same type of resource name at lower levels. Editing the message X in future versions can lead to the resource name helper Y to disappear, this can lead to unnecessary breaking changes for the users who rely on it.

**Comment by noahdietz** [comment]
I'm not sure what kinds of changes would result in a change to the generation of the helper and not also be a plain ol'breaking change in the proto surface. The situations I can think of that would result in a resource name helper no longer being generated are also standard breaking changes to the proto surface (e.g. field type changing, removal of a field, removal of an RPC, etc.) AFAIK. Did you have a specific scenario in mind?

**Comment by PierrickVoulet** [comment]
Correct, changes that lead resource name helpers to not be generated anymore would be part of a major release.

My point is that this FR would prevent breaking the users of those generated resource name helpers who use them for messages that are not at top-level.

**Comment by PierrickVoulet** [comment]
Please see https://github.com/googleads/google-ads-php/issues/747#issuecomment-1046058571 for a real life example of the type of unnecessary breaking changes that I was referring to in my previous comment.

**Comment by fiboknacky** [comment]
@noahdietz Noah, any chances this could be prioritized this year?

**Comment by noahdietz** [comment]
@fiboknacky yeah, this is actually done by #551:
> Increases the request message search depth for resource references/definitions.

This change is in our `v2-dev` branch, but once merged, it will be part of the core resource parsing logic for pre-migration clients as well (i.e. the generated surface Ads gets now will get this improvement without needing to generate the new v2 surface at all).

**Comment by noahdietz** [comment]
I think we need to time it with the PHP 7.3 drop so as to be able to more easily support the existing code until that point. cc @bshaffer who will handle that timing.

We are tracking the merge via https://github.com/googleapis/gapic-generator-php/issues/609, so you can "Follow" that issue for more. Then, we will need to update the googleapis/WORKSPACE...in that change there is something we will need to change in the Ads php bazel targets to keep y'all on the pre-migration surface, so those would be done together. I will contact y'all offline for that.

**Comment by bshaffer** [comment]
I'm hoping we can merge v2-dev and tag a release within the next 3 weeks, at which point the we'd have a tagged version of the GAPIC generator for ads to try out

**Comment by fiboknacky** [comment]
Thanks both. Will wait for your pings.
