### ISSUE TITLE
v2: remove experimental phrase and tag at some point

### ISSUE THREAD

**Issue by noahdietz** [googleapis/gapic-generator-php#594]
Remove the experimental tag/description added in https://github.com/googleapis/gapic-generator-php/pull/595 when we are sure the v2 surface is stable.

**Comment by noahdietz** [comment]
#595

**Comment by bshaffer** [comment]
Reminder that when we do this, we should also update the service class descriptions that were added in https://github.com/googleapis/gapic-generator-php/pull/638

**Comment by bshaffer** [comment]
fixed in https://github.com/googleapis/gapic-generator-php/pull/674
